openapi: "3.0.0"
info:
  version: 1.0.0
  title: Loopback sample
  description: This is to test the fesiblity of loopback.
  license:
    name: MIT
  contact:
    name: Nishant Shah
    email: nishant@tupronto.mx
servers:
  - url: http://localhost:5000
paths:
  /locations:
    post:
      summary: Create a new instance of the location and persist it into the data source.
      operationId: createLocation
      tags:
        - locations
      requestBody:
        description: A JSON object containing pet information
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Location"
      responses:
        "201":
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    get:
      summary: List all locations
      operationId: listLocations
      tags:
        - locations
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: A paged array of locations
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Locations"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Location:
      type: object
      required:
        - id
        - address
        - city
        - state
        - country
        - lat
        - long
        - zip
      properties:
        id:
          type: integer
          format: int64
        address:
          type: string
        city:
          type: string
        state:
          type: string
        country:
          type: string
        lat:
          type: number
          format: double
        long:
          type: number
          format: double
        zip:
          type: integer
          format: int64

    Locations:
      type: array
      items:
        $ref: "#/components/schemas/Location"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
